# Generated by Django 5.2.3 on 2025-06-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("ingredients", models.JSONField()),
                ("directions", models.JSONField()),
                ("link", models.URLField()),
                ("source", models.CharField(max_length=255)),
                ("ner", models.JSONField()),
                ("site", models.CharField(max_length=255)),
            ],
        ),
    ]
