# Generated by Django 5.2.3 on 2025-06-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="site",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
