# Generated by Django 5.2.3 on 2025-06-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_recipe_directions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="directions",
            field=models.JSONField(),
        ),
    ]
